### PR TITLE
Fixed some spelling, grammar, and formatting.

### PR DESCRIPTION
**Pull request by WarpEngineer**

### CODE REVIEW

**Review by nazmulidris — APPROVED** [review]
Looks great to me! 👏🏽 

Thank you for spending time on this. In order to make contributions to Ockam, please add yourself to the Contributor License Agreement. Once that is done (please let me know by replying to this comment) I will merge this PR.

- Accept the Ockam [Contributor License Agreement](https://github.com/build-trust/ockam-contributors/blob/main/CLA.md) by adding your Git/Github details in a row at the end of the [CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/blob/main/CONTRIBUTORS.csv) file in a separate pull request to the [build-trust/ockam-contributors](https://github.com/build-trust/ockam-contributors) repository.

- The easiest way to do this is to [edit the CONTRIBUTORS.csv](https://github.com/build-trust/ockam-contributors/edit/main/CONTRIBUTORS.csv) file in the github web UI and create a PR (and a single commit that will ensure that it is verified). The video below shows this in action.

https://github.com/build-trust/ockam-website/assets/2966499/363b5416-3b08-40fc-94b7-ce5ed3fb5af3

**Comment by WarpEngineer** [comment]
I've created a PR to accept the CLA. Thanks.

**Comment by nazmulidris** [comment]
@WarpEngineer Thank you for opening this [PR](https://github.com/build-trust/ockam-contributors/pull/259) to add yourself to the CLA. As soon as that is approved, I will merge this PR 🎉

**Comment by nazmulidris** [comment]
@WarpEngineer Thank you for accepting the CLA. I've merged your changes 👍🏽

**Comment by mrinalwadhwa** [comment]
@WarpEngineer thank you for an awesome first contribution 🥳

**Pull request merged**
