### PR TITLE
doc: simplify web app ex further

### PR DESCRIPTION
**Pull request by nazmulidris**

### CODE REVIEW

**Comment by nazmulidris** [comment]
@etorreborre 
I made the change that you requested in [this comment](https://github.com/build-trust/ockam-documentation/pull/39#discussion_r1244930402) in this PR.

**Comment by etorreborre** [comment]
@nazmulidris my proposal would be to actually even go one step further and have the initial application already have a line like
```python
pg_port = os.environ['APP_PG_PORT']
```
So that we can keep the motto "you don't have to change your application".

**Comment by nazmulidris** [comment]
> @nazmulidris my proposal would be to actually even go one step further and have the initial application already have a line like
> 
> ```python
> pg_port = os.environ['APP_PG_PORT']
> ```
> 
> So that we can keep the motto "you don't have to change your application".

That makes sense 👍🏽 I will add this change as another commit & let you know 👍🏽

**Comment by nazmulidris** [comment]
@etorreborre I just made the changes you requested 👍🏽

**Review by etorreborre — APPROVED** [review]
🚀

**Pull request merged**
